apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: lbtest

namespace: sandbox
resources:
- client.yaml

configMapGenerator:
- name: lbtest-go-src
  files:
  - go.mod
  - go.sum
  - main.go
