apiVersion: v1
kind: Service
metadata:
  name: lbtest-server
  namespace: sandbox
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: lbtest
    backend: "yes"
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lbtest
  name: lbtest-server
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbtest
  template:
    metadata:
      labels:
        app: lbtest
    spec:
      containers:
      - args:
        - --listen=:8080
        image: quay.io/cybozu/testhttpd:0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ingress-health
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
